export const DEVELOPER_WORKSPACE_COPY = {
  brandEyebrow: 'Developer Workspace',
  brand: 'Developer Console',
  sessionLabel: 'Primary developer session',
  nav: {
    dashboard: 'Dashboard',
    liveData: 'Live Monitor',
    elements: 'Elements',
    companies: 'Companies',
    tools: 'Developer Tools',
    profile: 'My Profile',
    notifications: 'Notifications',
    support: 'Support & Bug Reports',
  },
  pageMeta: {
    '/developer': {
      title: 'Dashboard',
      subtitle: 'Launch company sessions, inspect live activity, and keep internal control simple.',
    },
    '/live-data': {
      title: 'Live Monitor',
      subtitle: 'Monitor current user activity across web and mobile, with saved navigation and action history.',
    },
    '/elements': {
      title: 'Elements',
      subtitle: 'Internal UI lab for reusable date, time, and interaction patterns.',
    },
    '/companies': {
      title: 'Companies',
      subtitle: 'Tenant setup, branding, scoped sessions, and company-level controls.',
    },
    '/developer-tools': {
      title: 'Developer Tools',
      subtitle: 'Maintenance controls, demo data, system tasks, and protected developer actions.',
    },
    '/profile': {
      title: 'My Profile',
      subtitle: 'Update your developer identity and access credentials.',
    },
    '/notifications-center': {
      title: 'Notifications',
      subtitle: 'Developer inbox for system updates, ops alerts, and company-level signals.',
    },
    '/bug-reports': {
      title: 'Support & Bug Reports',
      subtitle: 'Track reported issues and follow the support queue from one place.',
    },
  },
  dashboard: {
    eyebrow: 'Internal control lane',
    title: 'Developer command center',
    description: 'Keep the developer workspace focused: launch tenant sessions fast, review live activity, and move straight into the tools that matter.',
    summary: {
      activeCompanies: 'Active companies',
      activeSessions: 'Active sessions',
      webSessions: 'Web sessions',
      mobileSessions: 'Mobile sessions',
    },
    actions: {
      liveData: 'Open Live Data',
      companies: 'Open Companies',
      elements: 'Open Elements',
      tools: 'Open Developer Tools',
      ops: 'Open Ops Console',
    },
    sections: {
      launcher: 'Company session launcher',
      launcherHelp: 'Start a one-hour scoped company session as Admin, Accountant, or Sales.',
      recentActivity: 'Recent activity',
      recentActivityHelp: 'Latest captured navigation and action history from live web/mobile sessions.',
      quickActions: 'Quick actions',
      quickActionsHelp: 'Jump directly into the developer surfaces you actually use.',
    },
    states: {
      launching: 'Launching...',
      fixedSession: 'Fixed 1h session',
      noCompanies: 'No active companies are available right now.',
      noRecentActivity: 'No tracked activity has been captured yet.',
      defaultBadge: 'Default',
    },
    roles: {
      admin: 'Admin',
      comptable: 'Accountant',
      rep: 'Sales',
    },
  },
  layout: {
    ops: 'Separate Ops Console',
    logout: 'Logout',
    lightTheme: 'Switch to light theme',
    darkTheme: 'Switch to dark theme',
  },
  liveData: {
    refresh: 'Refresh',
    loading: 'Loading live activity…',
    sections: {
      active: 'Current sessions',
      activeHelp: 'Fresh developer-visible sessions with the latest known page, screen, and action state.',
      history: 'Saved history',
      historyHelp: 'Append-only activity timeline captured from navigation events and business actions.',
      filters: 'Filters',
      filtersHelp: 'Narrow the snapshot by company, platform, or free-text search.',
    },
    filters: {
      allCompanies: 'All companies',
      allPlatforms: 'All platforms',
      web: 'Web',
      mobile: 'Mobile',
      searchPlaceholder: 'Search company, user, page, screen, or action',
    },
    cards: {
      activeSessions: 'Active sessions',
      activeUsers: 'Active users',
      webSessions: 'Web sessions',
      mobileSessions: 'Mobile sessions',
      latestEvent: 'Latest event',
    },
    table: {
      company: 'Company',
      user: 'User',
      platform: 'Platform',
      currentView: 'Current view',
      lastAction: 'Last action',
      lastSeen: 'Last seen',
      event: 'Event',
      status: 'Status',
    },
    states: {
      online: 'Online',
      stale: 'Stale',
      noActive: 'No matching sessions right now.',
      noHistory: 'No activity history matches the current filters.',
      noAction: 'No action captured yet',
      noView: 'No page or screen reported yet',
      notAvailable: 'Not available',
    },
  },
}
